<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAPS" ignored="0" name="Test(failed)" tests="2" failures="2" timestamp="2020-04-09T23:38:22 IST" time="0.078" errors="0">
  <testcase name="Method1" time="0.016" classname="exambleForTestNgGroups.ExambleForRetryFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at exambleForTestNgGroups.ExambleForRetryFailedTestCases.Method1(ExambleForRetryFailedTestCases.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Method1 -->
  <testcase name="Method2" time="0.0" classname="exambleForTestNgGroups.ExambleForRetryFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at exambleForTestNgGroups.ExambleForRetryFailedTestCases.Method2(ExambleForRetryFailedTestCases.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Method2 -->
</testsuite> <!-- Test(failed) -->
